title: Mi espacio Github
email: your-email@domain.com
description: > .
baseurl: "" 
url: "http://alvaro-rodriguez.github.io/" 
#twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
sass:
	sass_dir:_sass
include: ['_pages']
Kramdown:
	input:GFM
